name: CI

on:
  repository_dispatch:
    types: trigger-ci
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: Simple-Calculator-master
      continue-on-error: true
    - run: npm test 
      working-directory: Simple-Calculator-master
      continue-on-error: true
    - name: Notify Webhook
      run: |
        curl -X POST https://a4d4-85-230-190-125.ngrok-free.app/webhook \
        -H "Content-Type: application/json" \
        -d '{"text": "Hello world"}'

      