name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: Simple-Calculator-master
    - run: npm test -- --json --outputFile=test-results.json
      working-directory: Simple-Calculator-master
      continue-on-error: true
    - name: Parse test results
      run: |
        cat Simple-Calculator-master/test-results.json | jq -r '
          .testResults[] | 
          .assertionResults[] | 
          select(.status == "failed") | 
          "\(.fullName) | \(.location) | \(.failureMessages | join("\n"))"
        ' | while IFS='|' read -r test_name location error_message; do
          echo "::error file=${location}::${test_name}: ${error_message}"
        done