name: Deploy to Production

on:
  push:
    repository_dispatch:
      types: trigger-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here, such as ssh or API calls to cloud provider
      - name: Notify Webhook
        run: |
          curl -X POST https://hooks.slack.com/services/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 \
          -H "Content-Type: application/json" \
          -d '{"text": "Hello world"}'

      
