name: Deploy to Production

on:
  push:
    repository_dispatch:
      types: trigger-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here, such as ssh or API calls to cloud provider
      - name: Notify Webhook
        run: |
          curl -X POST https://5f45-85-230-190-125.ngrok-free.app/api/github-action \
          -H "Content-Type: application/json" \
          -d '{"status": "completed", "action": "github_action", "repository": "${{ github.repository }}"}'

      
